site_name: Flask 入门教程
site_description: 使用 Python 和 Flask 开发你的第一个 Web 程序
site_url: https://tutorial.helloflask.com
docs_dir: chapters
theme:
  name: material
  custom_dir: chapters/_templates
  logo: _assets/favicon.png
  favicon: _assets/favicon.png
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github
  language: zh
repo_url: https://github.com/helloflask/flask-tutorial
repo_name: helloflask/flask-tutorial
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/helloflask/flask-tutorial
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/helloflask
copyright: Copyright &copy; 2018 <a href="https://greyli.com" target="_blank" rel="noopener">Grey Li</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
  - toc:
        permalink: True
nav:
  - 简介: README.md
  - 前言: preface.md
  - 第 1 章：准备工作: ready.md
  - 第 2 章：Hello, Flask!: hello.md
  - 第 3 章：模板: template.md
  - 第 4 章：静态文件: static.md
  - 第 5 章：数据库: database.md
  - 第 6 章：模板优化: template2.md
  - 第 7 章：表单: form.md
  - 第 8 章：用户认证: login.md
  - 第 9 章：测试: test.md
  - 第 10 章：组织你的代码: organize.md
  - 第 11 章：部署上线: deploy.md
  - 小挑战: challenge.md
  - 后记: postscript.md
  - 教程主页↗: https://helloflask.com/book/3
  - 书稿源码↗: https://github.com/helloflask/flask-tutorial
  - 示例程序源码↗: https://github.com/helloflask/watchlist
  - HelloFlask 论坛↗: https://discuss.helloflask.com
plugins:
  - search
extra_css:
  - _assets/extra.css
